# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150L)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'db_table': 't_about',
                'verbose_name': 'about',
                'verbose_name_plural': 'about',
            },
        ),
        migrations.CreateModel(
            name='AboutCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_about_category',
                'verbose_name': 'about_category',
                'verbose_name_plural': 'about_category',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100L, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('createddate', models.DateField(blank=True, db_column='createdDate', default=b'2016-10-20', null=True, verbose_name='Date')),
            ],
            options={
                'db_table': 't_announcement',
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150L)),
                ('content', models.TextField(blank=True)),
                ('downloadurl', models.CharField(blank=True, max_length=200L)),
                ('createddate', models.DateField(blank=True, db_column='createdDate', null=True)),
            ],
            options={
                'db_table': 't_download',
                'verbose_name': 'download',
                'verbose_name_plural': 'download',
            },
        ),
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_download_category',
                'verbose_name': 'download_category',
                'verbose_name_plural': 'download_category',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150L, verbose_name='title')),
                ('content', models.TextField(blank=True, verbose_name='content')),
            ],
            options={
                'db_table': 't_faq',
                'verbose_name': 'faq',
                'verbose_name_plural': 'faq',
            },
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_faq_category',
                'verbose_name': 'faq_category',
                'verbose_name_plural': 'faq_category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255L, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('createddate', models.DateField(blank=True, db_column='createdDate', default=b'2016-10-20', null=True, verbose_name='Created Date')),
            ],
            options={
                'db_table': 't_news',
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_product_category',
                'verbose_name': 'product_category',
                'verbose_name_plural': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200L, verbose_name='Name')),
                ('product_simple_desc', models.TextField(blank=True, verbose_name='Simple Desc')),
                ('product_full_desc', models.TextField(blank=True, verbose_name='Full Desc')),
                ('product_pic', models.CharField(blank=True, max_length=200L, verbose_name='Picture Path')),
                ('product_order', models.IntegerField(verbose_name='Order')),
                ('createddate', models.DateField(blank=True, db_column='createdDate', default=b'2016-10-20', verbose_name='Created Date')),
                ('catid', models.ForeignKey(db_column='catid', on_delete=django.db.models.deletion.CASCADE, to='company.ProductCategory', verbose_name='catid')),
            ],
            options={
                'db_table': 't_products',
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150L)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'db_table': 't_service',
                'verbose_name': 'service',
                'verbose_name_plural': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_service_category',
                'verbose_name': 'service_category',
                'verbose_name_plural': 'service_category',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='catid',
            field=models.ForeignKey(db_column='catid', on_delete=django.db.models.deletion.CASCADE, to='company.ServiceCategory', verbose_name='catid'),
        ),
        migrations.AddField(
            model_name='faq',
            name='catid',
            field=models.ForeignKey(db_column='catid', on_delete=django.db.models.deletion.CASCADE, to='company.FaqCategory', verbose_name='catid'),
        ),
        migrations.AddField(
            model_name='download',
            name='catid',
            field=models.ForeignKey(db_column='catid', on_delete=django.db.models.deletion.CASCADE, to='company.DownloadCategory', verbose_name='catid'),
        ),
        migrations.AddField(
            model_name='about',
            name='catid',
            field=models.ForeignKey(db_column='catid', on_delete=django.db.models.deletion.CASCADE, to='company.AboutCategory', verbose_name='catid'),
        ),
    ]
