# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20161023_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '\u5173\u4e8e\u6211\u4eec', 'verbose_name_plural': '\u5173\u4e8e\u6211\u4eec'},
        ),
        migrations.AlterModelOptions(
            name='aboutcategory',
            options={'verbose_name': '\u5173\u4e8e\u6211\u4eec\u5206\u7c7b', 'verbose_name_plural': '\u5173\u4e8e\u6211\u4eec\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': '\u516c\u544a', 'verbose_name_plural': '\u516c\u544a'},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'verbose_name': '\u4e0b\u8f7d\u8d44\u6599', 'verbose_name_plural': '\u4e0b\u8f7d\u8d44\u6599'},
        ),
        migrations.AlterModelOptions(
            name='downloadcategory',
            options={'verbose_name': '\u4e0b\u8f7d\u8d44\u6599\u5206\u7c7b', 'verbose_name_plural': '\u4e0b\u8f7d\u8d44\u6599\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': '\u5e38\u89c1\u95ee\u9898', 'verbose_name_plural': '\u5e38\u89c1\u95ee\u9898'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name': '\u5e38\u89c1\u95ee\u9898\u5206\u7c7b', 'verbose_name_plural': '\u5e38\u89c1\u95ee\u9898\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '\u65b0\u95fb', 'verbose_name_plural': '\u65b0\u95fb'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': '\u4ea7\u54c1\u5206\u7c7b', 'verbose_name_plural': '\u4ea7\u54c1\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '\u4ea7\u54c1', 'verbose_name_plural': '\u4ea7\u54c1'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '\u670d\u52a1', 'verbose_name_plural': '\u670d\u52a1'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': '\u670d\u52a1\u5206\u7c7b', 'verbose_name_plural': '\u670d\u52a1\u5206\u7c7b'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='createddate',
            field=models.DateField(blank=True, db_column='createdDate', default=b'2016-10-29', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='createddate',
            field=models.DateField(blank=True, db_column='createdDate', default=b'2016-10-29', null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='products',
            name='createddate',
            field=models.DateField(blank=True, db_column='createdDate', default=b'2016-10-29', verbose_name='Created Date'),
        ),
    ]
