# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20161123_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='createddate',
            field=models.DateField(blank=True, db_column='createdDate', default=b'2016-11-25', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='createddate',
            field=models.DateField(blank=True, db_column='createdDate', default=b'2016-11-25', null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='products',
            name='createddate',
            field=models.DateField(blank=True, db_column='createdDate', default=b'2016-11-25', verbose_name='Created Date'),
        ),
    ]
